<?php

header('Content-Type: text/plain');

$allow = getenv('ENV') !== 'master' ? 'Disallow: /' : 'Allow: /';

$response = <<<ROBOTS
#robots.txt generated by netflex-sdk.
#The content of this file can be modified in the settings panel.
User-agent: *
$allow
ROBOTS;

die($response);
